repos:
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: bash -c 'cd frontend && npx tsc --noEmit'
        language: system
        types: [file]
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false

      - id: eslint-check
        name: ESLint Check
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        types: [file]
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
