# Product Manager Discovery Path - Spanish
path_id: product_manager
category: business
difficulty_range: beginner_to_expert

metadata:
  title: "Alquimista de Productos - Product Manager"
  short_description: "Forja productos perfectos en el crisol del mercado"
  long_description: |
    Eres un alquimista recién graduado del "Taller de Alquimia de Productos", 
    hábil en fusionar necesidades de usuarios, capacidades técnicas y objetivos 
    empresariales en productos poderosos. En este taller lleno de chispas de 
    innovación, cada iteración es un experimento alquímico, y tu objetivo es 
    crear productos perfectos que puedan cambiar el mundo.
  
  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "Taller de Alquimia de Productos"
  description: |
    El Taller de Alquimia de Productos es una forja mágica donde las ideas se 
    transforman en productos reales. Aquí, los product managers aprenden el 
    arte ancestral de equilibrar los deseos de los usuarios, las restricciones 
    técnicas y los objetivos empresariales para crear productos que resuenen 
    con millones de personas.
  
  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "El Desafío del Alquimista"
  description: |
    El Maestro de Estrategia te da la bienvenida al taller con una advertencia: 
    Deadline, el Tirano del Tiempo, está forzando a los equipos a sacrificar 
    la calidad del producto por velocidad. Mientras tanto, la Voz de los Usuarios 
    se vuelve más fuerte con demandas contradictorias. Debes encontrar la piedra 
    filosofal del product management - equilibrar calidad, velocidad y satisfacción del usuario.
  
  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: Lectura Mental de Usuarios
      description: Comprender profundamente las necesidades y comportamientos de usuarios
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: Visión Estratégica
      description: Crear estrategias de producto ganadoras
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: Alquimia de Prioridades
      description: Dominar el arte de priorizar funcionalidades
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: Orquestación de Armonía
      description: Alinear intereses de diversos stakeholders
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: Hechicería de Crecimiento
      description: Impulsar el crecimiento exponencial del producto
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: Maestría de Métricas
      description: Tomar decisiones basadas en insights de datos
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: Arquitectura de Ecosistema
      description: Construir plataformas de productos y ecosistemas
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: Génesis del Producto
    description: Lanzar exitosamente tu primer producto
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: Tiempo vs Calidad
    description: Entregar producto de calidad a pesar de la presión temporal
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: Producto de Mil Millones de Usuarios
    description: Crear un producto usado por millones
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: Escritor de Especificaciones
    description: Escribir tu primera especificación de producto
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: Defensor de Usuarios
    description: Implementar 20 funcionalidades solicitadas por usuarios
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: Alquimista de Ingresos
    description: Generar $1M en ingresos del producto
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: Sabio del Producto
    description: Completar todos los desafíos del producto
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: Recolección de Voces
      description: Realizar entrevistas a usuarios para recopilar insights
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: Escaneo del Mercado
      description: Analizar productos de la competencia
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: Diseño del Camino Futuro
      description: Crear un roadmap del producto
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: Alquimia de Funcionalidades
      description: Lanzar una funcionalidad importante del producto
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: Creación de Ecosistema
      description: Diseñar una plataforma de producto
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: Fórmula de Crecimiento
      description: Ejecutar experimentos de crecimiento para escalar el producto
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "Dominar técnicas de investigación de usuarios y empatía"
  - "Desarrollar pensamiento estratégico de producto"
  - "Aprender a priorizar funcionalidades efectivamente"
  - "Construir consenso entre diversos stakeholders"
  - "Usar datos para impulsar decisiones de producto"
  - "Crear y comunicar visión de producto"
  - "Equilibrar objetivos empresariales con necesidades de usuarios"
  - "Escalar productos desde la concepción hasta la madurez"

career_outcomes:
  - "Product Manager"
  - "Senior Product Manager"
  - "Product Director"
  - "Chief Product Officer"
  - "Consultor de Estrategia de Producto"
  - "Product Lead de Startup"
  - "Growth Product Manager"
  - "Platform Product Manager"
