# Product Manager Discovery Path - French
path_id: product_manager
category: business
difficulty_range: beginner_to_expert

metadata:
  title: "Alchimiste Produit - Product Manager"
  short_description: "Forgez des produits parfaits dans le creuset du marché"
  long_description: |
    Vous êtes un alchimiste fraîchement diplômé de l'"Atelier d'Alchimie Produit",
    expert dans la fusion des besoins utilisateurs, des capacités techniques et
    des objectifs commerciaux en produits puissants. Dans cet atelier rempli
    d'étincelles d'innovation, chaque itération est une expérience alchimique,
    et votre objectif est de créer des produits parfaits qui peuvent changer le monde.

  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "Atelier d'Alchimie Produit"
  description: |
    L'Atelier d'Alchimie Produit est une forge magique où les idées sont transformées
    en produits réels. Ici, les product managers apprennent l'art ancien d'équilibrer
    les désirs des utilisateurs, les contraintes techniques et les objectifs
    commerciaux pour créer des produits qui résonnent avec des millions de personnes.

  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "Le Défi de l'Alchimiste"
  description: |
    Maître Stratégie vous accueille dans l'atelier avec un avertissement : Délai,
    le Tyran du Temps, force les équipes à sacrifier la qualité du produit pour
    la vitesse. Pendant ce temps, la Voix des Utilisateurs devient plus forte
    avec des demandes contradictoires. Vous devez trouver la pierre philosophale
    du product management - équilibrer qualité, vitesse et satisfaction utilisateur.

  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: Lecture des Esprits Utilisateurs
      description: Comprendre profondément les besoins et comportements utilisateurs
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: Vision Stratégique
      description: Créer des stratégies produit gagnantes
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: Alchimie des Priorités
      description: Maîtriser l'art de la priorisation des fonctionnalités
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: Orchestration de l'Harmonie
      description: Aligner les intérêts de parties prenantes diverses
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: Sorcellerie de Croissance
      description: Diriger la croissance exponentielle du produit
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: Maîtrise des Métriques
      description: Prendre des décisions basées sur les insights de données
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: Architecture d'Écosystème
      description: Construire des plateformes produits et écosystèmes
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: Genèse du Produit
    description: Lancer avec succès votre premier produit
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: Temps vs Qualité
    description: Livrer un produit de qualité malgré la pression temporelle
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: Produit Milliard d'Utilisateurs
    description: Créer un produit utilisé par des millions
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: Rédacteur de Spécifications
    description: Écrire votre première spécification produit
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: Défenseur des Utilisateurs
    description: Implémenter 20 fonctionnalités demandées par les utilisateurs
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: Alchimiste des Revenus
    description: Générer $1M de revenus produit
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: Sage du Produit
    description: Compléter tous les défis produit
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: Collecte de Voix
      description: Mener des entretiens utilisateurs pour recueillir des insights
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: Scan du Marché
      description: Analyser les produits concurrents
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: Design du Chemin Futur
      description: Créer une roadmap produit
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: Alchimie de Fonctionnalité
      description: Lancer une fonctionnalité produit majeure
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: Création d'Écosystème
      description: Concevoir une plateforme produit
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: Formule de Croissance
      description: Mener des expériences de croissance pour échelle le produit
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "Maîtriser les techniques de recherche utilisateur et d'empathie"
  - "Développer la pensée stratégique produit"
  - "Apprendre à prioriser les fonctionnalités efficacement"
  - "Construire un consensus parmi diverses parties prenantes"
  - "Utiliser les données pour guider les décisions produit"
  - "Créer et communiquer la vision produit"
  - "Équilibrer les objectifs commerciaux avec les besoins utilisateurs"
  - "Écheller les produits de la conception à la maturité"

career_outcomes:
  - "Product Manager"
  - "Senior Product Manager"
  - "Product Director"
  - "Chief Product Officer"
  - "Consultant en Stratégie Produit"
  - "Product Lead de Startup"
  - "Growth Product Manager"
  - "Platform Product Manager"
