# Product Manager Discovery Path - Arabic
path_id: product_manager
category: business
difficulty_range: beginner_to_expert
metadata:
  title: "كيميائي المنتجات - Product Manager"
  short_description: "اصنع منتجات مثالية في بوتقة السوق"
  long_description: |
    أنت كيميائي حديث التخرج من "ورشة كيمياء المنتجات"، ماهر في دمج احتياجات 
    المستخدمين والقدرات التقنية والأهداف التجارية في منتجات قوية. في هذه الورشة 
    المليئة بشرارات الابتكار، كل تكرار هو تجربة كيميائية، وهدفك هو إنشاء 
    منتجات مثالية يمكنها تغيير العالم.
  
  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "ورشة كيمياء المنتجات"
  description: |
    ورشة كيمياء المنتجات هي مسبك سحري حيث تتحول الأفكار إلى منتجات حقيقية. 
    هنا يتعلم مديرو المنتجات الفن القديم لموازنة رغبات المستخدمين والقيود 
    التقنية والأهداف التجارية لإنشاء منتجات تلقى صدى لدى الملايين.
  
  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "تحدي الكيميائي"
  description: |
    يرحب بك أستاذ الاستراتيجية في الورشة مع تحذير: الموعد النهائي، طاغية الوقت، 
    يجبر الفرق على التضحية بجودة المنتج من أجل السرعة. وفي الوقت نفسه، يزداد 
    صوت المستخدمين بمطالب متضاربة. يجب أن تجد حجر الفلاسفة لإدارة المنتجات - 
    توازن الجودة والسرعة ورضا المستخدم.
  
  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: قراءة عقول المستخدمين
      description: فهم احتياجات وسلوكيات المستخدمين بعمق
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: الرؤية الاستراتيجية
      description: صياغة استراتيجيات منتجات رابحة
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: كيمياء الأولويات
      description: إتقان فن تحديد أولويات الميزات
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: أوركسترا التناغم
      description: توحيد مصالح أصحاب المصلحة المتنوعين
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: سحر النمو
      description: قيادة النمو الأسي للمنتج
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: إتقان المقاييس
      description: اتخاذ قرارات مبنية على رؤى البيانات
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: هندسة النظام البيئي
      description: بناء منصات المنتجات والأنظمة البيئية
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: تكوين المنتج
    description: إطلاق منتجك الأول بنجاح
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: الوقت مقابل الجودة
    description: تسليم منتج عالي الجودة رغم ضغط الوقت
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: منتج المليار مستخدم
    description: إنشاء منتج يستخدمه الملايين
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: كاتب المواصفات
    description: كتابة مواصفات منتجك الأولى
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: مدافع عن المستخدمين
    description: تنفيذ 20 ميزة طلبها المستخدمون
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: كيميائي الإيرادات
    description: تحقيق إيرادات بقيمة مليون دولار من المنتج
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: حكيم المنتجات
    description: إكمال جميع تحديات المنتج
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: جمع الأصوات
      description: إجراء مقابلات مع المستخدمين لجمع الرؤى
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: مسح السوق
      description: تحليل منتجات المنافسين
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: تصميم المسار المستقبلي
      description: إنشاء خارطة طريق المنتج
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: كيمياء الميزات
      description: إطلاق ميزة رئيسية في المنتج
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: إنشاء النظام البيئي
      description: تصميم منصة المنتج
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: معادلة النمو
      description: تشغيل تجارب النمو لتوسيع المنتج
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "إتقان تقنيات البحث والتعاطف مع المستخدمين"
  - "تطوير التفكير الاستراتيجي للمنتج"
  - "تعلم تحديد أولويات الميزات بفعالية"
  - "بناء إجماع بين أصحاب المصلحة المتنوعين"
  - "استخدام البيانات لقيادة قرارات المنتج"
  - "إنشاء وتوصيل رؤية المنتج"
  - "توازن الأهداف التجارية مع احتياجات المستخدمين"
  - "توسيع المنتجات من البداية إلى النضج"

career_outcomes:
  - "مدير منتجات"
  - "مدير منتجات أول"
  - "مدير إدارة المنتجات"
  - "كبير مسؤولي المنتجات"
  - "استشاري استراتيجية المنتجات"
  - "قائد المنتجات في الشركات الناشئة"
  - "مدير منتجات النمو"
  - "مدير منتجات المنصة"
