# Product Manager Discovery Path - Portuguese
path_id: product_manager
category: business
difficulty_range: beginner_to_expert
metadata:
  title: "Alquimista de Produtos - Product Manager"
  short_description: "Forje produtos perfeitos no crisol do mercado"
  long_description: |
    Você é um alquimista recém-formado na "Oficina de Alquimia de Produtos", especializado 
    em fundir necessidades dos usuários, capacidades técnicas e objetivos de negócios 
    em produtos poderosos. Nesta oficina cheia de faiscas de inovação, cada iteração 
    é um experimento alquímico, e seu objetivo é criar produtos perfeitos que 
    podem mudar o mundo.
  
  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "Oficina de Alquimia de Produtos"
  description: |
    A Oficina de Alquimia de Produtos é uma forja mágica onde ideias se transformam 
    em produtos reais. Aqui, gerentes de produto aprendem a arte antiga de equilibrar 
    desejos dos usuários, restrições técnicas e objetivos de negócios para criar 
    produtos que ressoam com milhões de pessoas.
  
  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "O Desafio do Alquimista"
  description: |
    O Mestre da Estratégia te recebe na oficina com um aviso: o Prazo, o Tirano 
    do Tempo, está forçando equipes a sacrificar a qualidade do produto pela velocidade. 
    Enquanto isso, a Voz dos Usuários fica mais alta com demandas conflitantes. 
    Você deve encontrar a pedra filosofal da gestão de produtos - equilibrar 
    qualidade, velocidade e satisfação do usuário.
  
  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: Leitura Mental do Usuário
      description: Entender profundamente necessidades e comportamentos dos usuários
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: Visão Estratégica
      description: Criar estratégias de produto vencedoras
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: Alquimia de Prioridades
      description: Dominar a arte da priorização de funcionalidades
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: Orquestração da Harmonia
      description: Alinhar interesses diversos dos stakeholders
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: Feitiçaria do Crescimento
      description: Impulsionar crescimento exponencial do produto
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: Maestria em Métricas
      description: Tomar decisões baseadas em insights de dados
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: Arquitetura de Ecossistema
      description: Construir plataformas de produtos e ecossistemas
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: Gênesis do Produto
    description: Lançar com sucesso seu primeiro produto
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: Tempo vs Qualidade
    description: Entregar produto de qualidade apesar da pressão temporal
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: Produto de Bilhões de Usuários
    description: Criar um produto usado por milhões
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: Escritor de Especificações
    description: Escrever sua primeira especificação de produto
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: Defensor do Usuário
    description: Implementar 20 funcionalidades solicitadas por usuários
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: Alquimista de Receita
    description: Gerar $1M em receita do produto
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: Sábio do Produto
    description: Completar todos os desafios do produto
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: Coleção de Vozes
      description: Conduzir entrevistas com usuários para obter insights
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: Escaneamento do Mercado
      description: Analisar produtos concorrentes
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: Design do Caminho Futuro
      description: Criar um roadmap do produto
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: Alquimia de Funcionalidades
      description: Lançar uma funcionalidade importante do produto
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: Criação de Ecossistema
      description: Projetar uma plataforma de produto
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: Fórmula de Crescimento
      description: Executar experimentos de crescimento para escalar o produto
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "Dominar técnicas de pesquisa de usuário e empatia"
  - "Desenvolver pensamento estratégico de produto"
  - "Aprender a priorizar funcionalidades efetivamente"
  - "Construir consenso entre stakeholders diversos"
  - "Usar dados para impulsionar decisões de produto"
  - "Criar e comunicar visão de produto"
  - "Equilibrar objetivos de negócio com necessidades do usuário"
  - "Escalar produtos da concepção à maturidade"

career_outcomes:
  - "Gerente de Produto"
  - "Gerente Sênior de Produto"
  - "Diretor de Produto"
  - "Chief Product Officer"
  - "Consultor de Estratégia de Produto"
  - "Líder de Produto em Startup"
  - "Gerente de Crescimento de Produto"
  - "Gerente de Produto de Plataforma"
