# Product Manager Discovery Path - Indonesian
path_id: product_manager
category: business
difficulty_range: beginner_to_expert

metadata:
  title: "Alkemis Produk - Product Manager"
  short_description: "Ciptakan produk sempurna di dalam tungku pasar"
  long_description: |
    Anda adalah alkemis yang baru lulus dari "Bengkel Alkimia Produk", terampil dalam
    menggabungkan kebutuhan pengguna, kemampuan teknis, dan tujuan bisnis menjadi produk
    yang kuat. Di bengkel yang penuh dengan percikan inovasi ini, setiap iterasi adalah
    eksperimen alkimia, dan tujuan Anda adalah menciptakan produk sempurna yang dapat
    mengubah dunia.

  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "Bengkel Alkimia Produk"
  description: |
    Bengkel Alkimia Produk adalah bengkel magis tempat ide-ide diubah menjadi produk
    nyata. Di sini, product manager mempelajari seni kuno menyeimbangkan keinginan
    pengguna, kendala teknis, dan tujuan bisnis untuk menciptakan produk yang resonan
    dengan jutaan orang.

  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "Tantangan Alkemis"
  description: |
    Master Strategi menyambut Anda di bengkel dengan peringatan: Deadline, Tiran Waktu,
    memaksa tim untuk mengorbankan kualitas produk demi kecepatan. Sementara itu,
    Suara Pengguna menjadi semakin keras dengan tuntutan yang bertentangan. Anda harus
    menemukan batu filosofis manajemen produk - menyeimbangkan kualitas, kecepatan,
    dan kepuasan pengguna.

  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: Pembacaan Pikiran Pengguna
      description: Memahami secara mendalam kebutuhan dan perilaku pengguna
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: Visi Strategis
      description: Menciptakan strategi produk yang menang
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: Alkimia Prioritas
      description: Menguasai seni prioritisasi fitur
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: Orkestrasi Harmoni
      description: Menyelaraskan kepentingan stakeholder yang beragam
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: Sihir Pertumbuhan
      description: Mendorong pertumbuhan produk eksponensial
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: Penguasaan Metrik
      description: Membuat keputusan berdasarkan wawasan data
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: Arsitektur Ekosistem
      description: Membangun platform produk dan ekosistem
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: Genesis Produk
    description: Berhasil meluncurkan produk pertama Anda
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: Waktu vs Kualitas
    description: Mengantarkan produk berkualitas meski dalam tekanan waktu
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: Produk Miliaran Pengguna
    description: Menciptakan produk yang digunakan jutaan orang
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: Penulis Spesifikasi
    description: Menulis spesifikasi produk pertama Anda
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: Advokat Pengguna
    description: Mengimplementasikan 20 fitur yang diminta pengguna
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: Alkemis Pendapatan
    description: Menghasilkan $1M pendapatan produk
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: Bijak Produk
    description: Menyelesaikan semua tantangan produk
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: Pengumpulan Suara
      description: Melakukan wawancara pengguna untuk mengumpulkan wawasan
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: Pemindaian Pasar
      description: Menganalisis produk pesaing
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: Desain Jalur Masa Depan
      description: Membuat roadmap produk
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: Alkimia Fitur
      description: Meluncurkan fitur produk utama
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: Penciptaan Ekosistem
      description: Merancang platform produk
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: Formula Pertumbuhan
      description: Menjalankan eksperimen pertumbuhan untuk menskalakan produk
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "Menguasai teknik riset pengguna dan empati"
  - "Mengembangkan pemikiran strategis produk"
  - "Belajar memprioritaskan fitur secara efektif"
  - "Membangun konsensus di antara stakeholder yang beragam"
  - "Menggunakan data untuk mendorong keputusan produk"
  - "Menciptakan dan mengkomunikasikan visi produk"
  - "Menyeimbangkan tujuan bisnis dengan kebutuhan pengguna"
  - "Menskalakan produk dari konsepsi hingga matang"

career_outcomes:
  - "Product Manager"
  - "Senior Product Manager"
  - "Product Director"
  - "Chief Product Officer"
  - "Konsultan Strategi Produk"
  - "Product Lead Startup"
  - "Growth Product Manager"
  - "Platform Product Manager"
