# Product Manager Discovery Path - German
path_id: product_manager
category: business
difficulty_range: beginner_to_expert

metadata:
  title: "Produkt-Alchemist - Product Manager"
  short_description: "Erschaffe perfekte Produkte im Marktschmelztiegel"
  long_description: |
    Du bist ein frisch ausgebildeter Alchemist in der "Produkt-Alchemie-Werkstatt", 
    geschickt darin, Nutzerbedürfnisse, technische Fähigkeiten und Geschäftsziele 
    zu mächtigen Produkten zu verschmelzen. In dieser von Innovationsfunken erfüllten 
    Werkstatt ist jede Iteration ein alchemistisches Experiment, und dein Ziel ist es, 
    perfekte Produkte zu schaffen, die die Welt verändern können.
  
  estimated_hours: 55
  skill_focus:
    - requirement_alchemy
    - roadmap_prophecy
    - team_coordination_magic
    - user_resonance
world_setting:
  name: "Produkt-Alchemie-Werkstatt"
  description: |
    Die Produkt-Alchemie-Werkstatt ist eine magische Schmiede, in der Ideen zu 
    echten Produkten verwandelt werden. Hier lernen Product Manager die uralte Kunst, 
    Nutzerwünsche, technische Beschränkungen und Geschäftsziele auszubalancieren, 
    um Produkte zu schaffen, die bei Millionen von Menschen Anklang finden.
  
  atmosphere: "dynamic_creative"
  visual_theme: "innovation_forge"
starting_scenario:
  title: "Die Herausforderung des Alchemisten"
  description: |
    Strategie-Meister begrüßt dich in der Werkstatt mit einer Warnung: Deadline, 
    der Zeit-Tyrann, zwingt Teams dazu, Produktqualität für Geschwindigkeit zu opfern. 
    Währenddessen wird die Stimme der Nutzer lauter mit widersprüchlichen Forderungen. 
    Du musst den Stein der Weisen des Produktmanagements finden - die Balance zwischen 
    Qualität, Geschwindigkeit und Nutzerzufriedenheit.
  
  initial_tasks:
    - understand_users
    - analyze_market
    - define_vision
skill_tree:
  core_skills:
    - id: user_research
      name: Nutzer-Gedankenlesen
      description: Nutzerbedürfnisse und -verhalten tiefgehend verstehen
      max_level: 10
      unlocks:
        - persona_creation
        - journey_mapping
    - id: product_strategy
      name: Strategische Vision
      description: Siegreiche Produktstrategien entwickeln
      max_level: 10
      unlocks:
        - competitive_analysis
        - positioning_mastery
    - id: feature_prioritization
      name: Prioritäts-Alchemie
      description: Die Kunst der Feature-Priorisierung meistern
      max_level: 10
      unlocks:
        - roadmap_planning
        - mvp_design
    - id: stakeholder_management
      name: Harmonie-Orchestrierung
      description: Verschiedene Stakeholder-Interessen ausrichten
      max_level: 10
      unlocks:
        - executive_communication
        - cross_team_collaboration
  advanced_skills:
    - id: growth_hacking
      name: Wachstums-Zauber
      description: Exponentielles Produktwachstum vorantreiben
      max_level: 15
      requires:
        - product_strategy
        - user_research
    - id: data_driven_decisions
      name: Metriken-Meisterschaft
      description: Entscheidungen auf Basis von Daten-Insights treffen
      max_level: 15
      requires:
        - feature_prioritization
        - user_research
    - id: platform_thinking
      name: Ökosystem-Architektur
      description: Produktplattformen und Ökosysteme aufbauen
      max_level: 15
      requires:
        - product_strategy
        - stakeholder_management
milestone_quests:
  - id: first_launch
    name: Produkt-Genesis
    description: Erfolgreich dein erstes Produkt launchen
    required_level: 5
    skills_tested:
      - user_research
      - feature_prioritization
    xp_reward: 600
    unlocks:
      - launch_specialist_badge
      - user_testimonials
  - id: deadline_balance
    name: Zeit vs Qualität
    description: Qualitätsprodukt trotz Zeitdruck liefern
    required_level: 10
    skills_tested:
      - stakeholder_management
      - product_strategy
    xp_reward: 1200
    unlocks:
      - balance_master_title
      - deadline_immunity
  - id: unicorn_product
    name: Milliarden-Nutzer-Produkt
    description: Ein von Millionen genutztes Produkt schaffen
    required_level: 20
    skills_tested:
      - growth_hacking
      - platform_thinking
    xp_reward: 2500
    unlocks:
      - legendary_pm_title
      - industry_influence
achievements:
  - id: first_spec
    name: Spezifikations-Schreiber
    description: Schreibe deine erste Produktspezifikation
    xp_reward: 100
    badge_type: bronze
  - id: user_champion
    name: Nutzer-Anwalt
    description: Implementiere 20 von Nutzern gewünschte Features
    xp_reward: 300
    badge_type: silver
  - id: revenue_generator
    name: Umsatz-Alchemist
    description: Generiere $1M Produktumsatz
    xp_reward: 600
    badge_type: gold
  - id: pm_legend
    name: Produkt-Weiser
    description: Bewältige alle Produkt-Herausforderungen
    xp_reward: 1200
    badge_type: platinum
example_tasks:
  beginner:
    - id: user_interviews
      type: analysis
      title: Stimmen-Sammlung
      description: Nutzerinterviews durchführen um Erkenntnisse zu sammeln
      skills_improved:
        - user_research
        - user_resonance
      xp_reward: 60
    - id: competitive_analysis
      type: analysis
      title: Markt-Scanning
      description: Konkurrenzprodukte analysieren
      skills_improved:
        - product_strategy
        - requirement_alchemy
      xp_reward: 70
  intermediate:
    - id: roadmap_creation
      type: creation
      title: Zukunfts-Pfad-Design
      description: Eine Produkt-Roadmap erstellen
      skills_improved:
        - roadmap_planning
        - roadmap_prophecy
      xp_reward: 180
    - id: feature_launch
      type: creation
      title: Feature-Alchemie
      description: Ein wichtiges Produktfeature launchen
      skills_improved:
        - feature_prioritization
        - stakeholder_management
      xp_reward: 200
  advanced:
    - id: platform_design
      type: creation
      title: Ökosystem-Erschaffung
      description: Eine Produktplattform designen
      skills_improved:
        - platform_thinking
        - product_strategy
      xp_reward: 400
    - id: growth_experiment
      type: analysis
      title: Wachstums-Formel
      description: Wachstumsexperimente für Produktskalierung durchführen
      skills_improved:
        - growth_hacking
        - data_driven_decisions
      xp_reward: 350
learning_objectives:
  - "Nutzerforschung und Empathie-Techniken meistern"
  - "Strategisches Produktdenken entwickeln"
  - "Effektive Feature-Priorisierung lernen"
  - "Konsens unter verschiedenen Stakeholdern aufbauen"
  - "Daten zur Steuerung von Produktentscheidungen nutzen"
  - "Produktvision schaffen und kommunizieren"
  - "Geschäftsziele mit Nutzerbedürfnissen balancieren"
  - "Produkte von der Entstehung bis zur Reife skalieren"

career_outcomes:
  - "Product Manager"
  - "Senior Product Manager"
  - "Product Director"
  - "Chief Product Officer"
  - "Produktstrategie-Berater"
  - "Startup Product Lead"
  - "Growth Product Manager"
  - "Platform Product Manager"
