# Environmental Scientist Discovery Path - Arabic
path_id: environmental_scientist
category: science
difficulty_range: beginner_to_expert

metadata:
  title: "حارس الكوكب - عالم البيئة"
  short_description: "احمِ الأرض من خلال الحلول البيئية المدعومة بالبيانات"
  long_description: |
    أنت عالم مبتدئ في "مركز الاستجابة المناخية العالمي"، حيث تتتبع أنظمة 
    المراقبة المدعومة بالذكاء الاصطناعي صحة الكوكب في الوقت الفعلي. مسلحاً 
    بالتكنولوجيا المتطورة ومعرفة علوم البيئة، ستعمل على فهم وعكس أضرار 
    المناخ بينما تطور حلولاً مستدامة للمستقبل.
  
  estimated_hours: 60
  skill_focus:
    - climate_modeling
    - ecosystem_analysis
    - pollution_tracking
    - sustainable_solutions
    - data_visualization

world_setting:
  name: "مركز الاستجابة المناخية العالمي"
  description: |
    مركز الاستجابة المناخية العالمي هو منشأة عالية التقنية حيث يستخدم 
    علماء البيئة الذكاء الاصطناعي وبيانات الأقمار الصناعية والبحث الميداني 
    لمراقبة وحماية النظم البيئية للأرض. يتسابق العلماء هنا مع الزمن لتطوير 
    الحلول قبل الوصول إلى نقاط التحول الحرجة.
  
  atmosphere: "urgent_hopeful"
  visual_theme: "eco_tech_fusion"

starting_scenario:
  title: "الإنذار الأحمر: أزمة المناخ"
  description: |
    الدكتورة غايا إيرث ترحب بك بأخبار مثيرة للقلق: عدة أنظمة بيئية تقترب 
    من عتبات حرجة. في الوقت نفسه، يواصل الرئيس التنفيذي بولوتو من شركة 
    ميغاكورب الممارسات المدمرة من أجل الربح. يجب عليك استخدام العلم والابتكار 
    لإنقاذ النظم البيئية بينما تكشف الجرائم البيئية للشركات.
  
  initial_tasks:
    - analyze_climate_data
    - identify_hotspots
    - propose_solutions
skill_tree:
  core_skills:
    - id: climate_science
      name: "ديناميكيات المناخ"
      description: "فهم النظم المناخية للأرض"
      max_level: 10
      unlocks:
        - weather_prediction
        - carbon_cycle_analysis
    - id: ecosystem_monitoring
      name: "الأنظمة الحية"
      description: "تتبع وتحليل النظم البيئية"
      max_level: 10
      unlocks:
        - biodiversity_assessment
        - habitat_mapping
    - id: pollution_detection
      name: "تتبع التلوث"
      description: "تحديد وتتبع الملوثات"
      max_level: 10
      unlocks:
        - water_quality_analysis
        - air_monitoring
    - id: sustainable_tech
      name: "الابتكار الأخضر"
      description: "تطوير تقنيات صديقة للبيئة"
      max_level: 10
      unlocks:
        - renewable_energy
        - circular_economy
  advanced_skills:
    - id: climate_modeling
      name: "التنبؤ بالمستقبل"
      description: "التنبؤ بسيناريوهات المناخ باستخدام الذكاء الاصطناعي"
      max_level: 15
      requires:
        - climate_science
        - ecosystem_monitoring
    - id: restoration_ecology
      name: "شفاء النظم البيئية"
      description: "استعادة البيئات المتضررة"
      max_level: 15
      requires:
        - ecosystem_monitoring
        - sustainable_tech
    - id: policy_influence
      name: "الدفاع عن البيئة"
      description: "تشكيل السياسات البيئية"
      max_level: 15
      requires:
        - pollution_detection
        - climate_science
milestone_quests:
  - id: first_discovery
    name: "كشف التلوث"
    description: "اكتشف انتهاكاً بيئياً كبيراً"
    required_level: 5
    skills_tested:
      - pollution_detection
      - ecosystem_monitoring
    xp_reward: 700
    unlocks:
      - whistleblower_badge
      - media_attention
  - id: ecosystem_save
    name: "بطل الموائل"
    description: "أنقذ نظاماً بيئياً مهدداً بالانقراض"
    required_level: 10
    skills_tested:
      - restoration_ecology
      - sustainable_tech
    xp_reward: 1400
    unlocks:
      - conservation_champion_title
      - wildlife_alliance
  - id: climate_solution
    name: "مغير قواعد اللعبة العالمي"
    description: "تطوير حل مناخي ثوري"
    required_level: 20
    skills_tested:
      - climate_modeling
      - policy_influence
    xp_reward: 2800
    unlocks:
      - earth_defender_title
      - un_recognition
achievements:
  - id: first_sample
    name: "باحث ميداني"
    description: "جمع وتحليل أول عينة بيئية"
    xp_reward: 100
    badge_type: bronze
  - id: data_detective
    name: "مكتشف الأنماط"
    description: "تحديد 10 شذوذات بيئية"
    xp_reward: 350
    badge_type: silver
  - id: solution_provider
    name: "بطل الابتكار"
    description: "تنفيذ 5 حلول مستدامة"
    xp_reward: 650
    badge_type: gold
  - id: planet_protector
    name: "حارس الأرض"
    description: "إكمال جميع التحديات البيئية"
    xp_reward: 1300
    badge_type: platinum
example_tasks:
  beginner:
    - id: water_testing
      type: analysis
      title: "تحليل المياه"
      description: "اختبار جودة المياه في الأنهار المحلية"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 65
    - id: carbon_footprint
      type: analysis
      title: "حاسبة الكربون"
      description: "قياس انبعاثات الكربون"
      skills_improved:
        - climate_science
        - sustainable_solutions
      xp_reward: 75
  intermediate:
    - id: habitat_restoration
      type: creation
      title: "إحياء النظام البيئي"
      description: "تصميم خطة استعادة الموائل"
      skills_improved:
        - restoration_ecology
        - ecosystem_analysis
      xp_reward: 190
    - id: pollution_tracking
      type: analysis
      title: "صيد التلوث"
      description: "تتبع التلوث إلى مصدره"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 220
  advanced:
    - id: climate_model
      type: creation
      title: "محاكي المستقبل"
      description: "بناء نموذج التنبؤ المناخي بالذكاء الاصطناعي"
      skills_improved:
        - climate_modeling
        - data_visualization
      xp_reward: 420
    - id: policy_proposal
      type: creation
      title: "قانون الأرض"
      description: "صياغة سياسة حماية البيئة"
      skills_improved:
        - policy_influence
        - sustainable_solutions
      xp_reward: 470
learning_objectives:
  - "إتقان تقنيات المراقبة البيئية"
  - "استخدام الذكاء الاصطناعي وعلم البيانات للتحليل البيئي"
  - "تطوير حلول التكنولوجيا المستدامة"
  - "فهم النظم المناخية والتنبؤات"
  - "تصميم مشاريع استعادة النظم البيئية"
  - "التأثير على السياسة البيئية والتنظيم"
  - "إيصال العلم للجمهور وصانعي السياسات"
  - "موازنة الاحتياجات البشرية مع الحماية البيئية"

career_outcomes:
  - "عالم البيئة"
  - "باحث المناخ"
  - "عالم أحياء الحفظ"
  - "استشاري بيئي"
  - "مدير الاستدامة"
  - "محلل السياسة البيئية"
  - "أخصائي استعادة النظم البيئية"
  - "مدير الاستدامة الرئيسي"
