# Environmental Scientist Discovery Path - Thai
# PLACEHOLDER FILE - ต้องการการแปล
path_id: environmental_scientist
category: science
difficulty_range: beginner_to_expert
metadata:
  title: "ผู้พิทักษ์โลก - นักวิทยาศาสตร์สิ่งแวดล้อม"
  short_description: "ปกป้องโลกด้วยโซลูชั่นสิ่งแวดล้อมที่ขับเคลื่อนด้วยข้อมูล"
  long_description: |
    คุณเป็นนักวิทยาศาสตร์รุ่นเยาว์ที่ "ศูนย์ตอบสนองภูมิอากาศโลก" ที่ซึ่งระบบ
    ติดตามที่ขับเคลื่อนด้วย AI ติดตามสุขภาพของโลกแบบเรียลไทม์ ด้วยเทคโนโลยี
    ล้ำสมัยและความรู้ด้านวิทยาศาสตร์สิ่งแวดล้อม คุณจะทำงานเพื่อเข้าใจและ
    พลิกฟื้นความเสียหายจากภูมิอากาศ พร้อมพัฒนาโซลูชั่นที่ยั่งยืนสำหรับอนาคต
  estimated_hours: 60
  skill_focus:
    - climate_modeling
    - ecosystem_analysis
    - pollution_tracking
    - sustainable_solutions
    - data_visualization
  translation_notice: ต้องการการแปล - This is a placeholder file
  original_language: en
  target_language: th
  generated_date: "2025-07-16T07:00:56.509Z"
world_setting:
  name: "ศูนย์ตอบสนองภูมิอากาศโลก"
  description: |
    ศูนย์ตอบสนองภูมิอากาศโลกเป็นสถานที่ไฮเทคที่นักวิทยาศาสตร์สิ่งแวดล้อม
    ใช้ AI ข้อมูลดาวเทียม และการวิจัยภาคสนามเพื่อติดตามและปกป้องระบบนิเวศ
    ของโลก นักวิทยาศาสตร์ที่นี่แข่งกับเวลาเพื่อพัฒนาโซลูชั่นก่อนที่จะถึง
    จุดวิกฤตที่ไม่อาจย้อนกลับได้
  atmosphere: urgent_hopeful
  visual_theme: eco_tech_fusion
starting_scenario:
  title: "รหัสแดง: วิกฤตภูมิอากาศ"
  description: |
    ดร.ไกอา เอิร์ธ ต้อนรับคุณด้วยข่าวที่น่าตกใจ: ระบบสิ่งแวดล้อมหลายระบบ
    กำลังเข้าใกล้เกณฑ์วิกฤต ในขณะเดียวกัน CEO พอลลูโต้ของเมก้าคอร์ปยังคง
    ดำเนินการทำลายล้างเพื่อผลกำไร คุณต้องใช้วิทยาศาสตร์และนวัตกรรมเพื่อ
    ช่วยเหลือระบบนิเวศ พร้อมเปิดโปงอาชญากรรมสิ่งแวดล้อมขององค์กร
  initial_tasks:
    - analyze_climate_data
    - identify_hotspots
    - propose_solutions
skill_tree:
  core_skills:
    - id: climate_science
      name: "พลวัตภูมิอากาศ"
      description: "เข้าใจระบบภูมิอากาศของโลก"
      max_level: 10
      unlocks:
        - weather_prediction
        - carbon_cycle_analysis
    - id: ecosystem_monitoring
      name: "ระบบสิ่งมีชีวิต"
      description: "ติดตามและวิเคราะห์ระบบนิเวศ"
      max_level: 10
      unlocks:
        - biodiversity_assessment
        - habitat_mapping
    - id: pollution_detection
      name: "การติดตามการปนเปื้อน"
      description: "ระบุและติดตามสารมลพิษ"
      max_level: 10
      unlocks:
        - water_quality_analysis
        - air_monitoring
    - id: sustainable_tech
      name: "นวัตกรรมสีเขียว"
      description: "พัฒนาเทคโนโลยีที่เป็นมิตรกับสิ่งแวดล้อม"
      max_level: 10
      unlocks:
        - renewable_energy
        - circular_economy
  advanced_skills:
    - id: climate_modeling
      name: "การพยากรณ์อนาคต"
      description: "ทำนายสถานการณ์ภูมิอากาศด้วย AI"
      max_level: 15
      requires:
        - climate_science
        - ecosystem_monitoring
    - id: restoration_ecology
      name: "การเยียวยาระบบนิเวศ"
      description: "ฟื้นฟูสิ่งแวดล้อมที่เสียหาย"
      max_level: 15
      requires:
        - ecosystem_monitoring
        - sustainable_tech
    - id: policy_influence
      name: "การสนับสนุนสิ่งแวดล้อม"
      description: "กำหนดนโยบายสิ่งแวดล้อม"
      max_level: 15
      requires:
        - pollution_detection
        - climate_science
milestone_quests:
  - id: first_discovery
    name: "เปิดโปงมลพิษ"
    description: "เปิดเผยการละเมิดสิ่งแวดล้อมครั้งใหญ่"
    required_level: 5
    skills_tested:
      - pollution_detection
      - ecosystem_monitoring
    xp_reward: 700
    unlocks:
      - whistleblower_badge
      - media_attention
  - id: ecosystem_save
    name: "วีรบุรุษแห่งถิ่นที่อยู่"
    description: "ช่วยเหลือระบบนิเวศที่ใกล้สูญพันธุ์"
    required_level: 10
    skills_tested:
      - restoration_ecology
      - sustainable_tech
    xp_reward: 1400
    unlocks:
      - conservation_champion_title
      - wildlife_alliance
  - id: climate_solution
    name: "ผู้เปลี่ยนเกมระดับโลก"
    description: "พัฒนาโซลูชั่นภูมิอากาศที่ก้าวหน้า"
    required_level: 20
    skills_tested:
      - climate_modeling
      - policy_influence
    xp_reward: 2800
    unlocks:
      - earth_defender_title
      - un_recognition
achievements:
  - id: first_sample
    name: "นักวิจัยภาคสนาม"
    description: "เก็บและวิเคราะห์ตัวอย่างสิ่งแวดล้อมชิ้นแรก"
    xp_reward: 100
    badge_type: bronze
  - id: data_detective
    name: "ผู้ค้นหารูปแบบ"
    description: "ระบุความผิดปกติทางสิ่งแวดล้อม 10 รายการ"
    xp_reward: 350
    badge_type: silver
  - id: solution_provider
    name: "แชมป์นวัตกรรม"
    description: "ดำเนินการโซลูชั่นที่ยั่งยืน 5 รายการ"
    xp_reward: 650
    badge_type: gold
  - id: planet_protector
    name: "ผู้พิทักษ์โลก"
    description: "เสร็จสิ้นความท้าทายด้านสิ่งแวดล้อมทั้งหมด"
    xp_reward: 1300
    badge_type: platinum
example_tasks:
  beginner:
    - id: water_testing
      type: analysis
      title: "การวิเคราะห์น้ำ"
      description: "ทดสอบคุณภาพน้ำในแม่น้ำท้องถิ่น"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 65
    - id: carbon_footprint
      type: analysis
      title: "เครื่องคำนวณคาร์บอน"
      description: "วัดการปล่อยคาร์บอน"
      skills_improved:
        - climate_science
        - sustainable_solutions
      xp_reward: 75
  intermediate:
    - id: habitat_restoration
      type: creation
      title: "การฟื้นฟูระบบนิเวศ"
      description: "ออกแบบแผนการฟื้นฟูที่อยู่อาศัย"
      skills_improved:
        - restoration_ecology
        - ecosystem_analysis
      xp_reward: 190
    - id: pollution_tracking
      type: analysis
      title: "การล่าหาการปนเปื้อน"
      description: "ติดตามมลพิษถึงแหล่งที่มา"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 220
  advanced:
    - id: climate_model
      type: creation
      title: "ตัวจำลองอนาคต"
      description: "สร้างแบบจำลองการทำนายภูมิอากาศด้วย AI"
      skills_improved:
        - climate_modeling
        - data_visualization
      xp_reward: 420
    - id: policy_proposal
      type: creation
      title: "กฎหมายแห่งแผ่นดิน"
      description: "ร่างนโยบายการคุ้มครองสิ่งแวดล้อม"
      skills_improved:
        - policy_influence
        - sustainable_solutions
      xp_reward: 470
learning_objectives:
  - "เชี่ยวชาญเทคนิคการติดตามสิ่งแวดล้อม"
  - "ใช้ AI และวิทยาศาสตร์ข้อมูลสำหรับการวิเคราะห์สิ่งแวดล้อม"
  - "พัฒนาโซลูชั่นเทคโนโลยีที่ยั่งยืน"
  - "เข้าใจระบบภูมิอากาศและการทำนาย"
  - "ออกแบบโครงการฟื้นฟูระบบนิเวศ"
  - "มีอิทธิพลต่อนโยบายและกฎระเบียบด้านสิ่งแวดล้อม"
  - "สื่อสารวิทยาศาสตร์สู่สาธารณะและผู้กำหนดนโยบาย"
  - "สร้างสมดุลระหว่างความต้องการของมนุษย์กับการคุ้มครองสิ่งแวดล้อม"
career_outcomes:
  - "นักวิทยาศาสตร์สิ่งแวดล้อม"
  - "นักวิจัยภูมิอากาศ"
  - "นักชีววิทยาการอนุรักษ์"
  - "ที่ปรึกษาสิ่งแวดล้อม"
  - "ผู้อำนวยการด้านความยั่งยืน"
  - "นักวิเคราะห์นโยบายสิ่งแวดล้อม"
  - "ผู้เชี่ยวชาญการฟื้นฟูระบบนิเวศ"
  - "ประธานเจ้าหน้าที่ฝ่ายความยั่งยืน"
