# Environmental Scientist Discovery Path - Russian
# PLACEHOLDER FILE - Требуется перевод
path_id: environmental_scientist
category: science
difficulty_range: beginner_to_expert
metadata:
  title: "Страж Планеты - Ученый-эколог"
  short_description: "Защитите Землю с помощью экологических решений на основе данных"
  long_description: |
    Вы - младший научный сотрудник в "Глобальном центре климатического реагирования", 
    где системы мониторинга на базе ИИ отслеживают здоровье планеты в реальном времени. 
    Вооруженный передовыми технологиями и знаниями в области экологических наук, вы будете 
    работать над пониманием и обращением вспять климатических изменений, разрабатывая 
    устойчивые решения для будущего.
  estimated_hours: 60
  skill_focus:
    - climate_modeling
    - ecosystem_analysis
    - pollution_tracking
    - sustainable_solutions
    - data_visualization
  translation_notice: Требуется перевод - This is a placeholder file
  original_language: en
  target_language: ru
  generated_date: "2025-07-16T07:00:56.508Z"
world_setting:
  name: "Глобальный центр климатического реагирования"
  description: |
    Глобальный центр климатического реагирования - это высокотехнологичный объект, где 
    ученые-экологи используют ИИ, спутниковые данные и полевые исследования для 
    мониторинга и защиты экосистем Земли. Ученые здесь борются со временем, чтобы 
    разработать решения до достижения критических точек невозврата.
  atmosphere: urgent_hopeful
  visual_theme: eco_tech_fusion
starting_scenario:
  title: "Код красный: Климатический кризис"
  description: |
    Доктор Гайя Земля встречает вас с тревожными новостями: множество экологических 
    систем приближаются к критическим порогам. Тем временем генеральный директор 
    Поллуто из МегаКорп продолжает разрушительные практики ради прибыли. Вы должны 
    использовать науку и инновации, чтобы спасти экосистемы, одновременно разоблачая 
    корпоративные экологические преступления.
  initial_tasks:
    - analyze_climate_data
    - identify_hotspots
    - propose_solutions
skill_tree:
  core_skills:
    - id: climate_science
      name: "Климатическая динамика"
      description: "Понимание климатических систем Земли"
      max_level: 10
      unlocks:
        - weather_prediction
        - carbon_cycle_analysis
    - id: ecosystem_monitoring
      name: "Живые системы"
      description: "Отслеживание и анализ экосистем"
      max_level: 10
      unlocks:
        - biodiversity_assessment
        - habitat_mapping
    - id: pollution_detection
      name: "Отслеживание загрязнений"
      description: "Идентификация и отслеживание загрязнителей"
      max_level: 10
      unlocks:
        - water_quality_analysis
        - air_monitoring
    - id: sustainable_tech
      name: "Зеленые инновации"
      description: "Разработка экологичных технологий"
      max_level: 10
      unlocks:
        - renewable_energy
        - circular_economy
  advanced_skills:
    - id: climate_modeling
      name: "Прогнозирование будущего"
      description: "Предсказание климатических сценариев с помощью ИИ"
      max_level: 15
      requires:
        - climate_science
        - ecosystem_monitoring
    - id: restoration_ecology
      name: "Исцеление экосистем"
      description: "Восстановление поврежденной окружающей среды"
      max_level: 15
      requires:
        - ecosystem_monitoring
        - sustainable_tech
    - id: policy_influence
      name: "Экологическая защита"
      description: "Формирование экологической политики"
      max_level: 15
      requires:
        - pollution_detection
        - climate_science
milestone_quests:
  - id: first_discovery
    name: "Разоблачение загрязнения"
    description: "Раскрыть крупное экологическое нарушение"
    required_level: 5
    skills_tested:
      - pollution_detection
      - ecosystem_monitoring
    xp_reward: 700
    unlocks:
      - whistleblower_badge
      - media_attention
  - id: ecosystem_save
    name: "Герой среды обитания"
    description: "Спасти находящуюся под угрозой экосистему"
    required_level: 10
    skills_tested:
      - restoration_ecology
      - sustainable_tech
    xp_reward: 1400
    unlocks:
      - conservation_champion_title
      - wildlife_alliance
  - id: climate_solution
    name: "Глобальный прорыв"
    description: "Разработать революционное климатическое решение"
    required_level: 20
    skills_tested:
      - climate_modeling
      - policy_influence
    xp_reward: 2800
    unlocks:
      - earth_defender_title
      - un_recognition
achievements:
  - id: first_sample
    name: "Полевой исследователь"
    description: "Собрать и проанализировать первый экологический образец"
    xp_reward: 100
    badge_type: bronze
  - id: data_detective
    name: "Искатель закономерностей"
    description: "Выявить 10 экологических аномалий"
    xp_reward: 350
    badge_type: silver
  - id: solution_provider
    name: "Чемпион инноваций"
    description: "Реализовать 5 устойчивых решений"
    xp_reward: 650
    badge_type: gold
  - id: planet_protector
    name: "Хранитель Земли"
    description: "Завершить все экологические вызовы"
    xp_reward: 1300
    badge_type: platinum
example_tasks:
  beginner:
    - id: water_testing
      type: analysis
      title: "Анализ воды"
      description: "Проверить качество воды в местных реках"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 65
    - id: carbon_footprint
      type: analysis
      title: "Углеродный калькулятор"
      description: "Измерить углеродные выбросы"
      skills_improved:
        - climate_science
        - sustainable_solutions
      xp_reward: 75
  intermediate:
    - id: habitat_restoration
      type: creation
      title: "Возрождение экосистемы"
      description: "Разработать план восстановления среды обитания"
      skills_improved:
        - restoration_ecology
        - ecosystem_analysis
      xp_reward: 190
    - id: pollution_tracking
      type: analysis
      title: "Охота за загрязнением"
      description: "Отследить загрязнение до его источника"
      skills_improved:
        - pollution_detection
        - data_visualization
      xp_reward: 220
  advanced:
    - id: climate_model
      type: creation
      title: "Симулятор будущего"
      description: "Создать модель климатического прогнозирования с ИИ"
      skills_improved:
        - climate_modeling
        - data_visualization
      xp_reward: 420
    - id: policy_proposal
      type: creation
      title: "Закон земли"
      description: "Разработать политику защиты окружающей среды"
      skills_improved:
        - policy_influence
        - sustainable_solutions
      xp_reward: 470
learning_objectives:
  - "Освоить методы экологического мониторинга"
  - "Использовать ИИ и науку о данных для экологического анализа"
  - "Разработать устойчивые технологические решения"
  - "Понимать климатические системы и прогнозы"
  - "Проектировать проекты восстановления экосистем"
  - "Влиять на экологическую политику и регулирование"
  - "Доносить науку до общественности и политиков"
  - "Балансировать человеческие потребности с охраной окружающей среды"
career_outcomes:
  - "Ученый-эколог"
  - "Исследователь климата"
  - "Биолог по охране природы"
  - "Экологический консультант"
  - "Директор по устойчивому развитию"
  - "Аналитик экологической политики"
  - "Специалист по экологическому восстановлению"
  - "Главный по устойчивому развитию"
