name: Schema Consistency Check

on:
  push:
    branches: [main, staging, development]
    paths:
      - 'frontend/prisma/**'
      - 'frontend/src/types/database.ts'
      - 'frontend/src/lib/repositories/**'
  pull_request:
    branches: [main, staging]
    paths:
      - 'frontend/prisma/**'
      - 'frontend/src/types/database.ts'
      - 'frontend/src/lib/repositories/**'

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_square_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Setup database
        working-directory: frontend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai_square_db
        run: |
          npx prisma migrate deploy
          npx prisma generate
      
      - name: Run schema validation
        working-directory: frontend
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: ai_square_db
        run: npx tsx scripts/validate-schema-consistency.ts
      
      - name: Check for schema drift
        if: failure()
        run: |
          echo "🚨 Schema inconsistency detected!"
          echo "Please ensure:"
          echo "1. Prisma schema matches TypeScript types"
          echo "2. All database changes go through Prisma migrations"
          echo "3. No manual database modifications"
          exit 1